"""Add widget support to channels and contacts

Revision ID: ff049b5c6f23
Revises: a1b2c3d4e5f6
Create Date: 2026-05-09 23:48:17.237448
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'ff049b5c6f23'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('widget_id', sa.String(length=255), nullable=True))
    op.add_column('channels', sa.Column('widget_secret', sa.Text(), nullable=True))
    op.add_column('channels', sa.Column('allowed_origins', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'channels', ['widget_id'])
    op.add_column('contacts', sa.Column('visitor_email', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('visitor_phone', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'visitor_phone')
    op.drop_column('contacts', 'visitor_email')
    op.drop_constraint(None, 'channels', type_='unique')
    op.drop_column('channels', 'allowed_origins')
    op.drop_column('channels', 'widget_secret')
    op.drop_column('channels', 'widget_id')
    # ### end Alembic commands ###
